name: Android Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write  # Grant write permission to the contents scope

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Run Gradle Build
    - name: Run Gradle
      run: ./gradlew assemble

    # Step 4: Compress Artifact Folder to ZIP
    - name: Zip Webview Godot Android Plugin
      run: zip -r webview-godot-android.zip plugin/demo/addons/webview-godot-android

    # Step 5a: Upload ZIP as Local Artifact for Push/PR
    - name: Upload ZIP as Local Artifact
      if: github.event_name != 'release'  # Only upload to local artifacts on push or PR
      uses: actions/upload-artifact@v4
      with:
        name: webview-godot-android-zip
        path: webview-godot-android.zip

    # Step 5b: Upload ZIP to GitHub Release
    - name: Upload ZIP to GitHub Release
      if: github.event_name == 'release'  # Only upload to the release event
      uses: ncipollo/release-action@v1
      with:
        artifacts: webview-godot-android.zip
        token: ${{ secrets.GITHUB_TOKEN }}
